packages:
  - "easy-archive-wasm"
  - "web"
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@types/node@25.9.3'
  - wasm-pack-inline@0.1.5
  - '@mui/core-downloads-tracker@9.1.1'
  - '@mui/icons-material@9.1.1'
  - '@mui/material@9.1.1'
  - '@mui/private-theming@9.1.1'
  - '@mui/styled-engine@9.1.1'
  - '@mui/system@9.1.1'
  - '@mui/types@9.1.1'
  - '@mui/utils@9.1.1'
